# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11JoD6bfX4QVn3lR6pSkh_AfWfOLeHOEP
"""

import streamlit as st
import joblib

# Load vectorizer
vectorizer = joblib.load("vectorizer.pkl")

# Load all models
models = {
    "Logistic Regression": joblib.load("LR_model.pkl"),
    "Decision Tree": joblib.load("DT_model.pkl"),
    "Gradient Boosting": joblib.load("GB_model.pkl"),

}

# Streamlit UI
st.title("Fake News Detection App")

st.markdown("Enter a news article text and choose a model to check if it's *Real* or *Fake*.")

# Text input
text_input = st.text_area("Enter News Text:", height=200)

# Model selection
model_choice = st.selectbox("Choose a model", list(models.keys()))

# Predict button
if st.button("Predict"):
    if text_input.strip() == "":
        st.warning("Please enter some text.")
    else:
        # Vectorize input
        input_vector = vectorizer.transform([text_input])

        # Predict
        prediction = models[model_choice].predict(input_vector)[0]

        # Output
        st.subheader("Result:")
        if prediction == 1:
            st.error("Fake News Detected")
        else:
            st.success("Real News")